### ISSUE TITLE
trying to put it in ZSH

### ISSUE THREAD

**Issue by xiaotinglian** [agehama/minimal_spectrum_analyzer#2]
im using oh-my-zsh theme agnoster
and trying to modify it with your analyuzer

setopt PROMPT_SUBST

#this part are original agnoster code

prompt_visual(){
    prompt_segment black default "%B%F{yellow}[$(tail -n 1 ~/Documents/build/analyzer_log)]"
}
build_prompt() {
  RETVAL=$?
  prompt_visual
  prompt_status
  prompt_virtualenv
  prompt_aws
  prompt_context
  prompt_dir
  prompt_git
  prompt_bzr
  prompt_hg
  prompt_end
}

TMOUT=1
TRAPALRM() {
  zle reset-prompt
}

currently it updates every second, and it looks very laggy, not smooth

i tried to change the TMOUT=1  to 0.x,    apparently , any number smaller than 1, will freeze  prompt_visual
do you have solution for this?
how did you get the smooth effect like the gif in your page

**Comment by romkatv** [comment]
The same issue was filed against powerlevel10k: https://github.com/romkatv/powerlevel10k/issues/2495. I've posted a solution there.
